# Generated by Django 4.2.3 on 2023-07-29 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=225)),
                ('extra', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
